language: php
php:
  - '7.4'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'

before_install:
  - export COMPOSER_MEMORY_LIMIT=-1
install: composer install
script: vendor/bin/phpunit
branches:
  except:
    - staging-test
