language: php
php:
  - '7.4'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'

before_script:
  - export COMPOSER_MEMORY_LIMIT=-1

script: vendor/bin/phpunit
install: composer install
branches:
  except:
    - staging-test
