language: php
php:
  - '7.4'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'

jobs:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty

install: composer install

before_script: export CLOUDINARY_URL=$(bash tools/allocate_test_cloud.sh php)
script: vendor/bin/phpunit

branches:
  except:
  - staging-test
