language: php
php:
  - '7.4'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'

before_install:
  - export COMPOSER_MEMORY_LIMIT=-1
install: composer install

before_script: >
  export CLOUDINARY_URL=$(bash tools/get_test_cloud.sh);
  echo cloud_name: "$(echo $CLOUDINARY_URL | cut -d'@' -f2)"
script: vendor/bin/phpunit

branches:
  except:
    - staging-test
